namespace FitLifeDesktopApp;

partial class ActivityForm
{
    private System.ComponentModel.IContainer components = null!;
    private Label lblTitle;
    private Label lblSubtitle;
    private Panel formPanel;
    private DataGridView grid;
    private Button btnAdd;
    private Button btnUpdate;
    private Button btnDelete;
    private Button btnClear;
    private Label lblStatus;
    private DateTimePicker dtDate;
    private System.Windows.Forms.Timer refreshTimer;
    private Label lbl0;
    private TextBox txtId;
    private Label lbl1;
    private TextBox txtMemberId;
    private Label lbl2;
    private TextBox txtSteps;
    private Label lbl3;
    private TextBox txtWorkout;
    private Label lbl4;
    private TextBox txtCalories;
    private Label lbl5;
    private TextBox txtWeight;
    private Label lbl6;
    private TextBox txtNotes;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null)) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        lblTitle = new Label();
        lblSubtitle = new Label();
        formPanel = new Panel();
        grid = new DataGridView();
        btnAdd = new Button();
        btnUpdate = new Button();
        btnDelete = new Button();
        btnClear = new Button();
        lblStatus = new Label();
        dtDate = new DateTimePicker();
        refreshTimer = new System.Windows.Forms.Timer(components);
        lbl0 = new Label();
        txtId = new TextBox();
        lbl0.AutoSize = true;
        lbl0.ForeColor = Color.FromArgb(71, 85, 105);
        lbl0.Location = new Point(30, 24);
        lbl0.Text = "ID";
        txtId.Location = new Point(30, 51);
        txtId.Name = "txtId";
        txtId.Size = new Size(240, 34);
        lbl1 = new Label();
        txtMemberId = new TextBox();
        lbl1.AutoSize = true;
        lbl1.ForeColor = Color.FromArgb(71, 85, 105);
        lbl1.Location = new Point(300, 24);
        lbl1.Text = "Member ID";
        txtMemberId.Location = new Point(300, 51);
        txtMemberId.Name = "txtMemberId";
        txtMemberId.Size = new Size(240, 34);
        lbl2 = new Label();
        txtSteps = new TextBox();
        lbl2.AutoSize = true;
        lbl2.ForeColor = Color.FromArgb(71, 85, 105);
        lbl2.Location = new Point(570, 24);
        lbl2.Text = "Steps";
        txtSteps.Location = new Point(570, 51);
        txtSteps.Name = "txtSteps";
        txtSteps.Size = new Size(240, 34);
        lbl3 = new Label();
        txtWorkout = new TextBox();
        lbl3.AutoSize = true;
        lbl3.ForeColor = Color.FromArgb(71, 85, 105);
        lbl3.Location = new Point(30, 92);
        lbl3.Text = "Workout";
        txtWorkout.Location = new Point(30, 119);
        txtWorkout.Name = "txtWorkout";
        txtWorkout.Size = new Size(240, 34);
        lbl4 = new Label();
        txtCalories = new TextBox();
        lbl4.AutoSize = true;
        lbl4.ForeColor = Color.FromArgb(71, 85, 105);
        lbl4.Location = new Point(300, 92);
        lbl4.Text = "Calories";
        txtCalories.Location = new Point(300, 119);
        txtCalories.Name = "txtCalories";
        txtCalories.Size = new Size(240, 34);
        lbl5 = new Label();
        txtWeight = new TextBox();
        lbl5.AutoSize = true;
        lbl5.ForeColor = Color.FromArgb(71, 85, 105);
        lbl5.Location = new Point(570, 92);
        lbl5.Text = "Weight kg";
        txtWeight.Location = new Point(570, 119);
        txtWeight.Name = "txtWeight";
        txtWeight.Size = new Size(240, 34);
        lbl6 = new Label();
        txtNotes = new TextBox();
        lbl6.AutoSize = true;
        lbl6.ForeColor = Color.FromArgb(71, 85, 105);
        lbl6.Location = new Point(30, 160);
        lbl6.Text = "Notes";
        txtNotes.Location = new Point(30, 187);
        txtNotes.Name = "txtNotes";
        txtNotes.Size = new Size(240, 34);
        ((System.ComponentModel.ISupportInitialize)grid).BeginInit();
        formPanel.SuspendLayout();
        SuspendLayout();
        lblTitle.AutoSize = true;
        lblTitle.Font = new Font("Segoe UI", 24F, FontStyle.Bold);
        lblTitle.ForeColor = Color.FromArgb(15, 23, 42);
        lblTitle.Location = new Point(30, 20);
        lblTitle.Text = "Activity Logs";
        lblSubtitle.AutoSize = true;
        lblSubtitle.ForeColor = Color.FromArgb(100, 116, 139);
        lblSubtitle.Location = new Point(34, 78);
        lblSubtitle.Text = "Track activities with automatic one-second refresh";
        formPanel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        formPanel.BackColor = Color.White;
        formPanel.Location = new Point(30, 120);
        formPanel.Name = "formPanel";
        formPanel.Size = new Size(1180, 323);
        formPanel.Controls.Add(lbl0);
        formPanel.Controls.Add(txtId);
        formPanel.Controls.Add(lbl1);
        formPanel.Controls.Add(txtMemberId);
        formPanel.Controls.Add(lbl2);
        formPanel.Controls.Add(txtSteps);
        formPanel.Controls.Add(lbl3);
        formPanel.Controls.Add(txtWorkout);
        formPanel.Controls.Add(lbl4);
        formPanel.Controls.Add(txtCalories);
        formPanel.Controls.Add(lbl5);
        formPanel.Controls.Add(txtWeight);
        formPanel.Controls.Add(lbl6);
        formPanel.Controls.Add(txtNotes);
        dtDate.Location = new Point(840, 51);
        dtDate.Name = "dtDate";
        dtDate.Size = new Size(280, 34);
        formPanel.Controls.Add(dtDate);
        btnAdd.Location = new Point(30, 249);
        btnAdd.Size = new Size(120, 42);
        btnAdd.Text = "Add";
        btnUpdate.Location = new Point(162, 249);
        btnUpdate.Size = new Size(120, 42);
        btnUpdate.Text = "Update";
        btnDelete.BackColor = Color.FromArgb(220, 38, 38);
        btnDelete.Location = new Point(294, 249);
        btnDelete.Size = new Size(120, 42);
        btnDelete.Text = "Delete";
        btnClear.BackColor = Color.FromArgb(100, 116, 139);
        btnClear.Location = new Point(426, 249);
        btnClear.Size = new Size(120, 42);
        btnClear.Text = "Clear";
        lblStatus.ForeColor = Color.FromArgb(100, 116, 139);
        lblStatus.Location = new Point(570, 255);
        lblStatus.Size = new Size(560, 42);
        lblStatus.TextAlign = ContentAlignment.MiddleLeft;
        formPanel.Controls.Add(btnAdd);
        formPanel.Controls.Add(btnUpdate);
        formPanel.Controls.Add(btnDelete);
        formPanel.Controls.Add(btnClear);
        formPanel.Controls.Add(lblStatus);
        grid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        grid.Location = new Point(30, 473);
        grid.Name = "grid";
        grid.Size = new Size(1180, 280);
        refreshTimer.Interval = 1000;
        AutoScaleDimensions = new SizeF(10F, 25F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(248, 250, 252);
        ClientSize = new Size(1240, 773);
        Controls.Add(lblTitle);
        Controls.Add(lblSubtitle);
        Controls.Add(formPanel);
        Controls.Add(grid);
        Name = "ActivityForm";
        Text = "Activity Logs";
        formPanel.ResumeLayout(false);
        formPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)grid).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }
}
